//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoterDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class voter
    {
        public int voterid { get; set; }
        public string votername { get; set; }
        public string vaddress { get; set; }
    }
}
